# Generated by Django 5.2.8 on 2025-11-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='buyer_unread',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='shop_unread',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
