# Generated by GPT-5-Codex on 2025-11-21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversation_buyer_unread_conversation_shop_unread"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together=set(),
        ),
    ]
