# Generated by Django 5.2.8 on 2025-11-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
