# Generated by Django 5.2.8 on 2025-11-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_saveditem_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='size_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
